<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('concursos_editais', function (Blueprint $table): void {
            $table->integer('cd_edital', true);
            $table->string('titulo');
            $table->string('orgao');
            $table->string('banca')->nullable();
            $table->char('uf', 2)->nullable();
            $table->string('cidade', 120)->nullable();
            $table->string('escolaridade', 120)->nullable();
            $table->text('cargos')->nullable();
            $table->decimal('salario_min', 10, 2)->nullable();
            $table->decimal('salario_max', 10, 2)->nullable();
            $table->date('dt_inicio_inscricao')->nullable();
            $table->date('dt_fim_inscricao');
            $table->text('link_edital');
            $table->string('fonte')->nullable();
            $table->enum('status', ['aberto', 'encerrado', 'previsto'])->default('aberto');
            $table->dateTime('dt_atualizacao')->useCurrent();

            $table->index(['status', 'dt_fim_inscricao']);
            $table->index(['uf', 'cidade']);
        });

        DB::table('concursos_editais')->insert($this->initialRows());
    }

    public function down(): void
    {
        Schema::dropIfExists('concursos_editais');
    }

    private function initialRows(): array
    {
        return [
            [
                'titulo' => 'Concurso Público para Ingresso no Corpo Auxiliar de Praças - CP-CAP 2026',
                'orgao' => 'Marinha do Brasil',
                'banca' => 'Marinha do Brasil',
                'uf' => null,
                'cidade' => null,
                'escolaridade' => 'Ensino médio/técnico',
                'cargos' => 'Corpo Auxiliar de Praças; 400 vagas; cargo após formado: Cabo; prova prevista em 27/09/2026',
                'salario_min' => null,
                'salario_max' => null,
                'dt_inicio_inscricao' => '2026-05-28',
                'dt_fim_inscricao' => '2026-06-28',
                'link_edital' => 'https://www.inscricao.marinha.mil.br/marinha/index_concursos.jsp?id_concurso=510',
                'fonte' => 'Portal de Concursos da Marinha; edital, inscrição e detalhes no acompanhamento oficial',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Concurso CBM AL 2026 - Oficiais e Praças',
                'orgao' => 'Corpo de Bombeiros Militar de Alagoas',
                'banca' => 'Cebraspe',
                'uf' => 'AL',
                'cidade' => 'Maceió/Arapiraca',
                'escolaridade' => 'Ensino médio',
                'cargos' => 'Oficial de Estado-Maior; Praça Bombeiro Militar Combatente; Praça Bombeiro Militar de Motomecanização; 172 vagas imediatas + 172 CR; provas em 11/10/2026',
                'salario_min' => 2354.67,
                'salario_max' => 11563.77,
                'dt_inicio_inscricao' => '2026-06-16',
                'dt_fim_inscricao' => '2026-07-21',
                'link_edital' => 'https://www.cebraspe.org.br/concursos/cbm_al_26',
                'fonte' => 'Governo de Alagoas / Cebraspe; edital e acompanhamento do concurso',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Concurso Guarda Municipal de Aracaju 2026',
                'orgao' => 'Prefeitura Municipal de Aracaju',
                'banca' => 'IDECAN',
                'uf' => 'SE',
                'cidade' => 'Aracaju',
                'escolaridade' => 'Ensino médio',
                'cargos' => 'Guarda Municipal de Aracaju; 100 vagas; prova objetiva prevista para 13/09/2026',
                'salario_min' => 4055.53,
                'salario_max' => 4055.53,
                'dt_inicio_inscricao' => '2026-05-29',
                'dt_fim_inscricao' => '2026-07-06',
                'link_edital' => 'https://www.aracaju.se.gov.br/userfiles/pdf/2026/guardamunicipal/EDITAL_N_01_DE_28_DE_MAIO_DE_2026_CONCURSO_GMA_2026_ABERTURA.pdf',
                'fonte' => 'Prefeitura de Aracaju; Edital nº 01/2026 - GMA/SSM/SEPLOG',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Concurso DETRAN AL 2026 - Analista e Assistente de Trânsito',
                'orgao' => 'Departamento Estadual de Trânsito de Alagoas',
                'banca' => 'Cebraspe',
                'uf' => 'AL',
                'cidade' => 'Maceió',
                'escolaridade' => 'Ensino superior',
                'cargos' => 'Analista de Trânsito em diversas especialidades; Assistente de Trânsito; 50 vagas imediatas + cadastro de reserva; provas em 02/08/2026',
                'salario_min' => 5454.54,
                'salario_max' => 7800.00,
                'dt_inicio_inscricao' => '2026-05-06',
                'dt_fim_inscricao' => '2026-06-29',
                'link_edital' => 'https://www.cebraspe.org.br/concursos/detran_al_26',
                'fonte' => 'Cebraspe / Governo de Alagoas; acompanhamento oficial do concurso',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Concurso PGE AL 2026 - Procurador do Estado',
                'orgao' => 'Procuradoria-Geral do Estado de Alagoas',
                'banca' => 'Cebraspe',
                'uf' => 'AL',
                'cidade' => 'Maceió',
                'escolaridade' => 'Superior em Direito e inscrição na OAB',
                'cargos' => 'Procurador do Estado de Alagoas - 1ª Classe; 10 vagas + cadastro de reserva; prova objetiva prevista para 11/07/2026',
                'salario_min' => 35877.28,
                'salario_max' => 35877.28,
                'dt_inicio_inscricao' => '2026-06-17',
                'dt_fim_inscricao' => '2026-06-21',
                'link_edital' => 'https://www.cebraspe.org.br/concursos/pge_al_26',
                'fonte' => 'Cebraspe; edital e acompanhamento oficial',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Concurso SEDES DF 2026 - Técnico e Especialista em Desenvolvimento Social',
                'orgao' => 'Secretaria de Estado de Desenvolvimento Social do Distrito Federal',
                'banca' => 'IADES',
                'uf' => 'DF',
                'cidade' => 'Brasília',
                'escolaridade' => 'Ensino médio e superior',
                'cargos' => 'Técnico em Desenvolvimento Social; Especialista em Desenvolvimento Social; 1.197 vagas + 3.591 CR; prova prevista para 06/09/2026',
                'salario_min' => 4320.16,
                'salario_max' => 6071.09,
                'dt_inicio_inscricao' => '2026-06-06',
                'dt_fim_inscricao' => '2026-07-13',
                'link_edital' => 'https://www.economia.df.gov.br/category/gestao-de-pessoas/concursos',
                'fonte' => 'Portal de Concursos do Governo do Distrito Federal; inclui HTML, Power BI e página da banca',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Franca SP - Concurso Público 04/2026',
                'orgao' => 'Prefeitura Municipal de Franca',
                'banca' => 'IBAM',
                'uf' => 'SP',
                'cidade' => 'Franca',
                'escolaridade' => null,
                'cargos' => 'Concurso Público - Edital nº 04/2026; 1 vaga informada no portal IBAM',
                'salario_min' => null,
                'salario_max' => null,
                'dt_inicio_inscricao' => '2026-06-10',
                'dt_fim_inscricao' => '2026-07-09',
                'link_edital' => 'https://www.ibamsp-concursos.org.br/',
                'fonte' => 'IBAM SP; página oficial de concursos públicos no Estado de São Paulo',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Franca SP - Concurso Público 05/2026',
                'orgao' => 'Prefeitura Municipal de Franca',
                'banca' => 'IBAM',
                'uf' => 'SP',
                'cidade' => 'Franca',
                'escolaridade' => null,
                'cargos' => 'Concurso Público - Edital nº 05/2026',
                'salario_min' => null,
                'salario_max' => null,
                'dt_inicio_inscricao' => '2026-06-10',
                'dt_fim_inscricao' => '2026-07-09',
                'link_edital' => 'https://www.ibamsp-concursos.org.br/',
                'fonte' => 'IBAM SP; página oficial de concursos públicos no Estado de São Paulo',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Franca SP - Concurso Público 06/2026',
                'orgao' => 'Prefeitura Municipal de Franca',
                'banca' => 'IBAM',
                'uf' => 'SP',
                'cidade' => 'Franca',
                'escolaridade' => null,
                'cargos' => 'Concurso Público - Edital nº 06/2026',
                'salario_min' => null,
                'salario_max' => null,
                'dt_inicio_inscricao' => '2026-06-11',
                'dt_fim_inscricao' => '2026-07-09',
                'link_edital' => 'https://www.ibamsp-concursos.org.br/',
                'fonte' => 'IBAM SP; página oficial de concursos públicos no Estado de São Paulo',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Elias Fausto SP - Concurso Público 02/2026',
                'orgao' => 'Prefeitura Municipal de Elias Fausto',
                'banca' => 'IBAM',
                'uf' => 'SP',
                'cidade' => 'Elias Fausto',
                'escolaridade' => null,
                'cargos' => 'Concurso Público nº 02/2026; 1 vaga informada no portal IBAM',
                'salario_min' => null,
                'salario_max' => null,
                'dt_inicio_inscricao' => '2026-06-20',
                'dt_fim_inscricao' => '2026-07-21',
                'link_edital' => 'https://www.ibamsp-concursos.org.br/',
                'fonte' => 'IBAM SP; inscrições abertas',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Concurso Público Alto Rio Doce MG - Edital 01/2026',
                'orgao' => 'Prefeitura Municipal de Alto Rio Doce',
                'banca' => 'IBGP',
                'uf' => 'MG',
                'cidade' => 'Alto Rio Doce',
                'escolaridade' => null,
                'cargos' => 'Provimento de cargos públicos do quadro de pessoal municipal; provas objetiva, discursiva, títulos e prática conforme cargo',
                'salario_min' => null,
                'salario_max' => null,
                'dt_inicio_inscricao' => '2026-05-19',
                'dt_fim_inscricao' => '2026-06-20',
                'link_edital' => 'https://www.altoriodoce.mg.gov.br/portal/editais/0/3/427/',
                'fonte' => 'Prefeitura Municipal de Alto Rio Doce; edital, anexos e retificações',
                'status' => 'aberto',
            ],
            [
                'titulo' => 'Concurso Público NAV Brasil 01/2026',
                'orgao' => 'NAV Brasil Serviços de Navegação Aérea S.A.',
                'banca' => 'FGV',
                'uf' => null,
                'cidade' => null,
                'escolaridade' => 'Ensino médio, técnico e superior',
                'cargos' => '128 vagas + CR; Assistente Social; Técnicos de Infraestrutura e Manutenção; Operador de Torre de Controle; Advogado; Analistas; Engenheiros; Meteorologista; prova objetiva prevista para 02/08/2026',
                'salario_min' => 4632.10,
                'salario_max' => 10868.68,
                'dt_inicio_inscricao' => '2026-04-27',
                'dt_fim_inscricao' => '2026-05-28',
                'link_edital' => 'https://conhecimento.fgv.br/concursos/navbrasil26',
                'fonte' => 'NAV Brasil / FGV; edital, cronograma, resultados, gabaritos e documentos no acompanhamento',
                'status' => 'encerrado',
            ],
            [
                'titulo' => 'Concurso SES MG 2026 - Especialista em Políticas e Gestão da Saúde',
                'orgao' => 'Secretaria de Estado de Saúde de Minas Gerais',
                'banca' => 'IBGP',
                'uf' => 'MG',
                'cidade' => 'Belo Horizonte',
                'escolaridade' => 'Ensino superior',
                'cargos' => 'Especialista em Políticas e Gestão da Saúde - EPGS; 380 vagas + cadastro de reserva; provas previstas para 03/05/2026',
                'salario_min' => 4287.02,
                'salario_max' => 4287.02,
                'dt_inicio_inscricao' => '2026-03-04',
                'dt_fim_inscricao' => '2026-04-02',
                'link_edital' => 'https://www.saude.mg.gov.br/noticias/inscricoes-para-concurso-publico-da-secretaria-de-estado-de-saude-comecam-nesta-quarta-feira-4-3/',
                'fonte' => 'SES MG / IBGP; edital e informações oficiais',
                'status' => 'encerrado',
            ],
            [
                'titulo' => 'Concurso SEFAZ RN 2025/2026 - Auditor Fiscal',
                'orgao' => 'Secretaria de Estado da Fazenda do Rio Grande do Norte',
                'banca' => 'Cebraspe',
                'uf' => 'RN',
                'cidade' => 'Natal',
                'escolaridade' => 'Ensino superior',
                'cargos' => 'Auditor Fiscal de Receitas Estaduais; 50 vagas + cadastro de reserva; provas objetivas em 21 e 22/03/2026',
                'salario_min' => 13283.64,
                'salario_max' => 13283.64,
                'dt_inicio_inscricao' => '2025-12-26',
                'dt_fim_inscricao' => '2026-01-16',
                'link_edital' => 'https://www.cebraspe.org.br/concursos/sefaz_rn_25_auditor',
                'fonte' => 'Cebraspe / SEAD RN; concurso com resultado e homologação em 2026',
                'status' => 'encerrado',
            ],
            [
                'titulo' => 'Concurso TCE RN 2026',
                'orgao' => 'Tribunal de Contas do Estado do Rio Grande do Norte',
                'banca' => 'Cebraspe',
                'uf' => 'RN',
                'cidade' => 'Natal',
                'escolaridade' => 'Ensino médio e superior',
                'cargos' => 'Analista Administrativo; Auditor de Controle Externo; Médico; Técnico Administrativo; 55 vagas + cadastro de reserva; provas em 11 e 12/04/2026',
                'salario_min' => 6173.51,
                'salario_max' => 15553.30,
                'dt_inicio_inscricao' => '2026-01-14',
                'dt_fim_inscricao' => '2026-02-04',
                'link_edital' => 'https://www.cebraspe.org.br/concursos/tce_rn_25',
                'fonte' => 'Cebraspe / TCE RN; acompanhamento com resultados das provas e etapas posteriores',
                'status' => 'encerrado',
            ],
            [
                'titulo' => 'Concurso FAPEAL 2026 - Gestor Especializado em Ciência e Tecnologia',
                'orgao' => 'Fundação de Amparo à Pesquisa do Estado de Alagoas',
                'banca' => 'Cebraspe',
                'uf' => 'AL',
                'cidade' => 'Maceió',
                'escolaridade' => 'Ensino superior',
                'cargos' => 'Gestor Especializado em Ciência e Tecnologia; áreas de Administração, Contabilidade, Economia, Jornalismo e Tecnologia da Informação; 10 vagas imediatas + 16 CR; prova em 16/08/2026',
                'salario_min' => 5767.15,
                'salario_max' => 5767.15,
                'dt_inicio_inscricao' => '2026-05-15',
                'dt_fim_inscricao' => '2026-06-19',
                'link_edital' => 'https://www.cebraspe.org.br/concursos/fapeal_26',
                'fonte' => 'Cebraspe / Governo de Alagoas; edital e acompanhamento oficial',
                'status' => 'encerrado',
            ],
            [
                'titulo' => 'Concurso PCDF 2026 - Delegado de Polícia',
                'orgao' => 'Polícia Civil do Distrito Federal',
                'banca' => 'Cebraspe',
                'uf' => 'DF',
                'cidade' => 'Brasília',
                'escolaridade' => 'Superior em Direito',
                'cargos' => 'Delegado de Polícia; 50 vagas + 100 CR; prova em 14/06/2026',
                'salario_min' => 26690.15,
                'salario_max' => 26690.15,
                'dt_inicio_inscricao' => null,
                'dt_fim_inscricao' => '2026-04-27',
                'link_edital' => 'https://www.economia.df.gov.br/category/gestao-de-pessoas/concursos',
                'fonte' => 'Portal de Concursos do Governo do Distrito Federal; página da banca e documentos do concurso',
                'status' => 'encerrado',
            ],
            [
                'titulo' => 'Concurso PM BA 2026 - Soldado e Oficial',
                'orgao' => 'Polícia Militar do Estado da Bahia',
                'banca' => null,
                'uf' => 'BA',
                'cidade' => null,
                'escolaridade' => 'Ensino médio e superior',
                'cargos' => 'Concurso autorizado; previsão de 2.500 vagas para Soldado e 200 para Oficial',
                'salario_min' => 4012.00,
                'salario_max' => null,
                'dt_inicio_inscricao' => null,
                'dt_fim_inscricao' => '2099-12-31',
                'link_edital' => 'https://blog.grancursosonline.com.br/concurso-pm-ba-autorizado-2026/',
                'fonte' => 'Previsto/autorizado; data sentinela usada por limitação do schema',
                'status' => 'previsto',
            ],
            [
                'titulo' => 'Concurso INEA RJ 2026',
                'orgao' => 'Instituto Estadual do Ambiente do Rio de Janeiro',
                'banca' => null,
                'uf' => 'RJ',
                'cidade' => null,
                'escolaridade' => null,
                'cargos' => 'Concurso autorizado; previsão de 150 vagas em diversas áreas; edital previsto após autorização',
                'salario_min' => null,
                'salario_max' => null,
                'dt_inicio_inscricao' => null,
                'dt_fim_inscricao' => '2099-12-31',
                'link_edital' => 'https://www.estrategiaconcursos.com.br/blog/concurso-inea-rj-e-autorizado/',
                'fonte' => 'Previsto/autorizado; data sentinela usada por limitação do schema',
                'status' => 'previsto',
            ],
            [
                'titulo' => 'Concurso Defensoria Pública RJ 2026',
                'orgao' => 'Defensoria Pública do Estado do Rio de Janeiro',
                'banca' => null,
                'uf' => 'RJ',
                'cidade' => null,
                'escolaridade' => 'Superior em Direito',
                'cargos' => 'Defensor Público; previsão de 75 vagas; banca a definir',
                'salario_min' => null,
                'salario_max' => null,
                'dt_inicio_inscricao' => null,
                'dt_fim_inscricao' => '2099-12-31',
                'link_edital' => 'https://folha.qconcursos.com/n/concursos-rio-de-janeiro',
                'fonte' => 'Previsto; data sentinela usada por limitação do schema',
                'status' => 'previsto',
            ],
            [
                'titulo' => 'Concurso IDAF ES 2026',
                'orgao' => 'Instituto de Defesa Agropecuária e Florestal do Espírito Santo',
                'banca' => 'IDCAP',
                'uf' => 'ES',
                'cidade' => null,
                'escolaridade' => 'Ensino técnico e superior',
                'cargos' => 'Técnico de Fiscalização e Desenvolvimento Agropecuário; Fiscal Estadual Agropecuário; 14 vagas + CR',
                'salario_min' => 3828.59,
                'salario_max' => 7547.78,
                'dt_inicio_inscricao' => null,
                'dt_fim_inscricao' => '2099-12-31',
                'link_edital' => 'https://www.estrategiaconcursos.com.br/blog/concursos-sudeste/',
                'fonte' => 'Previsto com banca definida; data sentinela usada por limitação do schema',
                'status' => 'previsto',
            ],
            [
                'titulo' => 'Concurso SEAP RN 2026',
                'orgao' => 'Secretaria de Administração Penitenciária do Rio Grande do Norte',
                'banca' => null,
                'uf' => 'RN',
                'cidade' => null,
                'escolaridade' => null,
                'cargos' => 'Concurso autorizado para 300 vagas; edital previsto para 2026',
                'salario_min' => null,
                'salario_max' => null,
                'dt_inicio_inscricao' => null,
                'dt_fim_inscricao' => '2099-12-31',
                'link_edital' => 'https://www.sead.rn.gov.br/materia/governo-autoriza-concurso-para-a-secretaria-de-administracao-penitenciaria-com-300-vagas',
                'fonte' => 'Previsto/autorizado; data sentinela usada por limitação do schema',
                'status' => 'previsto',
            ],
        ];
    }
};
